server:
  port: 8085

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: test
    password: sys
  datasource2:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: test2
    password: sys




