# springBoot内置容器的配置
server:
  # 端口号
  port: 8086
  servlet:
    # 项目前缀
    context-path: /dataSource

spring:
  # 数据源配置
  datasource:
    # mysql数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC  
    username: root
    password: ok
    # druid配置
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,wall,stat  
      # 初始化数量
      initialSize: 5
      #   最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 连接超时时间
      maxWait: 60000
      # 打开psCache, 对支持游标的数据库性能提升巨大
      poolPreparedStatements: true
      # 指定每个连接PsCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 验证数据库连接的查询语句
      validationQuery: select 'x'
      # 当连接空闲时，是否执行连接测试
      testWhileIdle: true 
      # 当从连接池借用连接时，是否测试该连接 
      testOnBorrow: false  
      # 在连接归还到连接池时是否测试该连接
      testOnReturn: false  
      # 打开mergeSql，慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    
  # thymeleaf 模板引擎配置
  thymeleaf:
    cache: false  
    # thymeleaf模板对html5没有结束符的标签解决
    mode: LEGACYHTML5
    # thymeleaf修饰的动态页面 自定义根目录(默认就是templates)
    prefix: classpath:/templates/
    
# mybatis配置
mybatis:
  # 映射xml的文件位置
  mapper-locations: classpath:mybatis/*.xml
  # 实体类所在包，简化xml中resultMap中实体类的全类名写法
  type-aliases-package: demo.domain

    
