DROP TABLE IF EXISTS TEST_USER;
CREATE TABLE TEST_USER(
	USER_ID VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '用户唯一id',
	USERNAME VARCHAR(20) NOT NULL COMMENT '用户名，即昵称',
	LOGINNAME VARCHAR(20) NOT NULL COMMENT '登录名，即登录账号',
	PASSWORD VARCHAR(20) NOT NULL COMMENT '用户密码',
	MAIL VARCHAR(20) NOT NULL COMMENT '用户邮箱',
	IDCARD VARCHAR(18) NOT NULL COMMENT '用户身份证',
	SEX INT NOT NULL COMMENT '性别：1)男    2)女  3)无法识别',
	HOBBY_ID INT(2) NOT NULL COMMENT '爱好编号， 外键：HOBBY',
	WORKDAY VARCHAR(20) NOT NULL COMMENT '工作日：1)周一  2)周二  3)周三  4)周四  5)周五  6)周六  7)周日'
) COMMENT='用户表';


DROP TABLE IF EXISTS TEST_HOBBY;
CREATE TABLE TEST_HOBBY(
	HOBBY_ID INT(2) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '爱好编号',
	HOBBY_CONTENT VARCHAR(20) NOT NULL COMMENT '爱好内容'
) COMMENT='爱好表';
INSERT INTO TEST_HOBBY(HOBBY_CONTENT) VALUE
('足球'),('篮球'),('羽毛球'),('网球'),('排球'),('铅球'),('排球');

SELECT * FROM TEST_HOBBY